### PR TITLE
Fix Brazil PhoneNumber Regexp

### PR DESCRIPTION
**Pull request by rwrz**
For some reason, all REGEX was using `\\d` instead of `\d`... this should fix the problem. 
And Brazilian numbers changed mobile numbers to begin with an `9` before the area code... fixed this regex too.

- [x] Are you fixing a bug? 
- [x] Detail how the bug is invoked currently.
Currently, any BR number should work, because of a typo on REGEX. `\\d` instead of `\d`.
Someone should verify all others files, since it is a typo...

- [x] Detail the original, incorrect behavior.
There is a problem with BR mobile numbers too. Now, all brazilian mobile numbers starts with a `9`.

- [x] Detail the new, expected behavior.
Fixed to accept the 9.

- [ ] Add a `CHANGELOG.md` entry for the fix.
Sorry, can someone do that? I'm changing here in Github...

- [ ] Provide a test case
Sorry, can someone do that? I'm changing here in Github...

### CODE REVIEW

**Review by malukenho — APPROVED** [review]

**Comment by froschdesign** [comment]
All unit tests are successful - with and without these changes?!

**Review by Ocramius — CHANGES_REQUESTED** [review]
Requires addition of example phone numbers in the test suite

**Comment by michalbundyra** [comment]
@rwrz Would you be able to review my changes?
`\\` doesn't matter in all of these regular expression as in PHP `\\` is the same as `\` and it's fine. All other files are also using `\\` so I revert that change for consistency.

I've updated area code for fixed and mobile phones and added 9 after area code for mobiles.
It looks like mobile phones must have 11 digits in total.

**Comment by rwrz** [comment]
@webimpress all good man, tested with a few real numbers... working 100%.

**Comment by michalbundyra** [comment]
Thanks, @rwrz!

**Pull request merged**
