### PR TITLE
Locale aware validators now implement LocaleAwareValidatorInterface

### PR DESCRIPTION
**Pull request by fabiang**
Relating zendframework/zend-validator#109

### CODE REVIEW

**Comment by weierophinney** [comment]
Tentatively scheduling for 2.8.0 release, pending review of the zend-validator patch.

In the meantime, can you please rebase from current develop?

**Comment by weierophinney** [comment]
You'll need to rebase against current develop.

**Comment by fabiang** [comment]
Now it's fine.

**Comment by froschdesign** [comment]
Waiting for [zend-validator 2.10.0](https://github.com/zendframework/zend-validator/pull/109)

**Comment by weierophinney** [comment]
As noted in zendframework/zend-validator#109, we will either be removing i18n features from the core of zend-validator for a v3 release, or, alternately, will not be doing a v3 release in favor of a parallel component to which developers can migrate later. As such, we closed that particular issue, making this one obsolete.

**Pull request closed without merging**
